import type { Product, Category } from '@/lib/types';
import { Shirt, Laptop, Utensils, Home, Gamepad2, Watch } from 'lucide-react';

export const categories: Category[] = [
  { id: 'electronics', name: 'Electronics', icon: Laptop, image: 'https://placehold.co/400x300.png' },
  { id: 'clothing', name: 'Clothing', icon: Shirt, image: 'https://placehold.co/400x300.png' },
  { id: 'home-kitchen', name: 'Home & Kitchen', icon: Utensils, image: 'https://placehold.co/400x300.png' },
  { id: 'furniture', name: 'Furniture', icon: Home, image: 'https://placehold.co/400x300.png' },
  { id: 'gaming', name: 'Gaming', icon: Gamepad2, image: 'https://placehold.co/400x300.png' },
  { id: 'watches', name: 'Watches', icon: Watch, image: 'https://placehold.co/400x300.png' },
];

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Quantum Core Laptop',
    description: 'Experience unparalleled performance with the new Quantum Core laptop. Featuring a 16-inch display, the latest generation processor, and all-day battery life.',
    price: 1299.99,
    rating: 4.8,
    reviewCount: 256,
    category: 'electronics',
    brand: 'Quantum',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    stock: 50,
    tags: ['laptop', 'powerful', 'new'],
  },
  {
    id: 'p2',
    name: 'Aero-Flex T-Shirt',
    description: 'Stay cool and comfortable with the Aero-Flex T-Shirt. Made from breathable, moisture-wicking fabric, it\'s perfect for workouts or casual wear.',
    price: 39.99,
    rating: 4.5,
    reviewCount: 1024,
    category: 'clothing',
    brand: 'Aero',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    stock: 200,
    tags: ['shirt', 'comfort', 'sale'],
  },
  {
    id: 'p3',
    name: 'Chrono-Shift Watch',
    description: 'A timeless piece of craftsmanship. The Chrono-Shift watch features a stainless steel case, sapphire crystal glass, and automatic movement.',
    price: 499.99,
    rating: 4.9,
    reviewCount: 150,
    category: 'watches',
    brand: 'Timeless',
    images: ['https://placehold.co/600x600.png'],
    stock: 30,
    tags: ['watch', 'luxury', 'classic'],
  },
  {
    id: 'p4',
    name: 'Vortex Gaming Console',
    description: 'Enter the next generation of gaming with the Vortex console. Stunning 4K graphics, lightning-fast load times, and a revolutionary controller.',
    price: 499.99,
    rating: 4.7,
    reviewCount: 512,
    category: 'gaming',
    brand: 'Vortex',
    images: ['https://placehold.co/600x600.png'],
    stock: 100,
    tags: ['gaming', 'console', 'new'],
  },
  {
    id: 'p5',
    name: 'Ergo-Luxe Office Chair',
    description: 'The Ergo-Luxe chair provides ultimate comfort and support for long hours of work. Fully adjustable with premium materials.',
    price: 349.99,
    rating: 4.6,
    reviewCount: 89,
    category: 'furniture',
    brand: 'LuxeHome',
    images: ['https://placehold.co/600x600.png'],
    stock: 15,
    tags: ['chair', 'office', 'comfort'],
  },
  {
    id: 'p6',
    name: 'FusionBlend Blender',
    description: 'Create smoothies, soups, and more with the powerful FusionBlend blender. 1200W motor and durable glass pitcher.',
    price: 89.99,
    rating: 4.4,
    reviewCount: 320,
    category: 'home-kitchen',
    brand: 'KitchenPro',
    images: ['https://placehold.co/600x600.png'],
    stock: 150,
    tags: ['blender', 'kitchen', 'sale'],
  },
  {
    id: 'p7',
    name: 'Nova Wireless Earbuds',
    description: 'Immerse yourself in crystal-clear audio with Nova Wireless Earbuds. Active noise cancellation and up to 30 hours of playtime.',
    price: 149.99,
    rating: 4.7,
    reviewCount: 780,
    category: 'electronics',
    brand: 'NovaAudio',
    images: ['https://placehold.co/600x600.png'],
    stock: 120,
    tags: ['audio', 'earbuds', 'new'],
  },
  {
    id: 'p8',
    name: 'Terra-Trek Hiking Boots',
    description: 'Conquer any trail with Terra-Trek Hiking Boots. Waterproof, durable, and designed for maximum grip and comfort.',
    price: 129.99,
    rating: 4.9,
    reviewCount: 450,
    category: 'clothing',
    brand: 'Pathfinder',
    images: ['https://placehold.co/600x600.png'],
    stock: 80,
    tags: ['shoes', 'hiking', 'outdoor'],
  },
];
