import type { Product, Category } from '@/lib/types';
import { Shirt, User } from 'lucide-react';

export const categories: Category[] = [
  { id: 'mens', name: 'Mens', icon: User, image: 'https://placehold.co/400x300.png', bannerImage: 'https://placehold.co/1200x400.png' },
  { id: 'half-sleeve', name: 'Half Sleeve T-shirt', icon: Shirt, image: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg_1-dRP5Srup6Ukf2hf_HXKws9B2_u_x9_hY0vi2qF9kEp9sOd5ZPuHT9fVv5Prcg8tafAzF-E2fw6CfGP1gLoxiIqsrPVZxAJ1wZssw-uAvineJbwUuJ0yK91h02Gnn-ZFEVSfqn_eGTWYl5rmCm1pQvqchiauK0kD3blLbNNZErMc6aALqvHzjkwzrg/s320/643106a391a9e-square.jpg', bannerImage: 'https://placehold.co/1200x400.png' },
  { id: 'full-sleeve', name: 'Full Sleeve T-shirt', icon: Shirt, image: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgDCUB_-5LzYY1l4yZKR1xJ450aF6Q2HwkVi3ope0LhMEpfL-Rn3cOjvqXegtdFSShhUXAy1Vk8a7ee20ubnuUXcuXC4rafTNvouxmIan07_MdA6jvp_RcsQeYaT3hT_T8yDMPRLgTLrI-ODEQrMEREqvD4-lDgk4OqMroibW9rJxoz0vbyJCC75BkPOyM/s320/61c4131d3073e-square.jpg', bannerImage: 'https://placehold.co/1200x400.png' },
  { id: 'drop-shoulder', name: 'Drop Shoulder T-shirt', icon: Shirt, image: 'https://placehold.co/400x300.png', bannerImage: 'https://placehold.co/1200x400.png' },
  { id: 'sports-tshirt', name: 'Sports T-shirt', icon: Shirt, image: 'https://placehold.co/400x300.png', bannerImage: 'https://placehold.co/1200x400.png' },
  { id: 'polo-tshirt', name: 'Polo T-shirt', icon: Shirt, image: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgO-yMlAsx8RlDNnXCCpKoo1gT25kg43_toC9ccRBYldcV6bAQADPsL8dS-OUtfy8kqy3eFm0MvXRDOuGs3TmU4OWULHIKjto_Dz47ew5Eirqt61cNdNNJ7aOIP4vSkD8R8ZmtR7ommjbKMTcIJi1pqr2-L3x4ycnquhh5RUzwYfeBLMxVdyaj10b8Ex90/s320/621784538389b-square.jpg', bannerImage: 'https://placehold.co/1200x400.png' },
  { id: 'shirt', name: 'Shirt', icon: Shirt, image: 'https://placehold.co/400x300.png', bannerImage: 'https://placehold.co/1200x400.png' },
  { id: 'underwear', name: 'Underwear', icon: Shirt, image: 'https://placehold.co/400x300.png', bannerImage: 'https://placehold.co/1200x400.png' },
];

export const products: Product[] = [
  // Half Sleeve T-shirts
  {
    id: 'p1',
    name: 'Graphic Half-Sleeve Tee',
    description: 'Express yourself with this cool graphic tee.',
    price: 24.99,
    rating: 4.6,
    reviewCount: 345,
    category: 'half-sleeve',
    brand: 'Urban Basics',
    images: ['https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg_1-dRP5Srup6Ukf2hf_HXKws9B2_u_x9_hY0vi2qF9kEp9sOd5ZPuHT9fVv5Prcg8tafAzF-E2fw6CfGP1gLoxiIqsrPVZxAJ1wZssw-uAvineJbwUuJ0yK91h02Gnn-ZFEVSfqn_eGTWYl5rmCm1pQvqchiauK0kD3blLbNNZErMc6aALqvHzjkwzrg/s320/643106a391a9e-square.jpg'],
    stock: 150,
    tags: ['t-shirt', 'cotton', 'new'],
  },
  {
    id: 'p8',
    name: 'Vintage Wash T-Shirt',
    description: 'This half-sleeve tee has a soft, vintage feel from the first wear. A perfect addition to your casual rotation.',
    price: 29.99,
    rating: 4.7,
    reviewCount: 280,
    category: 'half-sleeve',
    brand: 'Retro Threads',
    images: ['https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhNlw5SIZtcF-i5XzzpxDrm8FEqw4l1H6D9d5nqN5wVubtNixl6n4dp3GYzw484HUsMYVm3XCsRal6Hs4_Cce7Xbox47wOYtizG1BqgBfa769XO3kS01xf9VLUZ7vFZf-2EiCLPZbwDkcLbU8cVzhm7JaYP2ysgUIOpYhu9m6o77lvQFPz7vh18ByQAHFc/s320/615081c1422bc-square.jpg'],
    stock: 90,
    tags: ['vintage', 't-shirt', 'sale'],
  },
  {
    id: 'p11',
    name: 'Classic Crew Neck Tee',
    description: 'A timeless classic, this half-sleeve crew neck is a wardrobe essential. Made from 100% premium cotton for ultimate comfort.',
    price: 22.0,
    rating: 4.5,
    reviewCount: 250,
    category: 'half-sleeve',
    brand: 'StreetStyle',
    images: ['https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiJ2GHcYW3V1wWlIr8-x7Q5fJhaECLGV9RdntP8b_XoqAgOctqtVMotElXiq6W7N7r4rI9EOGSY2N-m2UgD01YPN7_dIxWPKrQZ8AjbayBnRVXuMlHt2FHls48Ips2VPEPkGRawJpp0lJCZrqA5fmLMv0qN7wPIAoWFppZnRLiiG6NVwmXdITWEAdf_acY/s320/61507e0206e56-square.jpg'],
    stock: 130,
    tags: ['graphic', 't-shirt', 'new'],
  },
  
  // Full Sleeve T-shirts
  {
    id: 'p2',
    name: 'Long-Sleeve Henley',
    description: 'Stay warm and stylish with our full-sleeve Henley shirt. Perfect for layering in cooler weather.',
    price: 39.99,
    rating: 4.5,
    reviewCount: 210,
    category: 'full-sleeve',
    brand: 'Aero',
    images: ['https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgDCUB_-5LzYY1l4yZKR1xJ450aF6Q2HwkVi3ope0LhMEpfL-Rn3cOjvqXegtdFSShhUXAy1Vk8a7ee20ubnuUXcuXC4rafTNvouxmIan07_MdA6jvp_RcsQeYaT3hT_T8yDMPRLgTLrI-ODEQrMEREqvD4-lDgk4OqMroibW9rJxoz0vbyJCC75BkPOyM/s320/61c4131d3073e-square.jpg'],
    stock: 80,
    tags: ['henley', 'full-sleeve', 'casual'],
  },
  {
    id: 'p10',
    name: 'Thermal Full Sleeve',
    description: 'A warm and cozy thermal full sleeve shirt.',
    price: 35.0,
    rating: 4.4,
    reviewCount: 95,
    category: 'full-sleeve',
    brand: 'Aero',
    images: ['https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiQ1gm5hLnZAyYUepuJx6oWbZs27G16baeRSHx3dS4hDgMfoq7HuanQtMGWpMA2IFYcqz8hL4H5-NAxOVqjSpN2oen3W5YBNcMOB1QnPnypOrwihKmWohOdUg3nrZFA0GZ6EGDYk2eFHImAL1-9GXRka5wyj4nBuOLtBBrMHwhsmU4ABjrVvvcKgdEd1L0/s320/6194db5781779-square.jpg'],
    stock: 85,
    tags: ['thermal', 'full-sleeve', 'winter'],
  },
  {
    id: 'p13',
    name: 'Stylish Full Sleeve',
    description: 'A stylish full sleeve shirt for any occasion.',
    price: 42.0,
    rating: 4.6,
    reviewCount: 115,
    category: 'full-sleeve',
    brand: 'StreetStyle',
    images: ['https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjI-znpih2L48tKRDnSdf3frpv97U5Sc9mOroef5qAyrjEywdkcl-o2dZHkdSZTUc1CXUwfE_2VEKYKgYsecvoccEoizIkjWDRVlOSYcXS8NX1taRLwh6VwTtNf0yVcuSLjCt_X8s6JFLgq8FviUGjvrwVIeqkrYGTdV0fpTbEkutzZuzPla5evPu6qdRY/s320/618295f85eee1-square.jpg'],
    stock: 70,
    tags: ['stylish', 'full-sleeve'],
  },
  {
    id: 'p14',
    name: 'Casual Full Sleeve',
    description: 'A comfortable full sleeve for casual wear.',
    price: 38.0,
    rating: 4.3,
    reviewCount: 85,
    category: 'full-sleeve',
    brand: 'Urban Basics',
    images: ['https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj0Ufx_yBX6I78H0fHx2pA1OYSFrTMs5mYsCBz1nrRj51IvdDKqcRzMgzdyPWEO5i6BG0KegOblyiXwG7zGb4QEi_m9G4h3l8IXBHmKNsj3kCzNeLaKICVeWHwq5qFKaPq4LhdoYOpWXChyvghgIsIVqd-g_naCgFwC6ghZ1Zl2HGw01p-p0Tj0jHPn3Q0/s320/618295f859863-square.jpg'],
    stock: 95,
    tags: ['casual', 'full-sleeve'],
  },

  // Polo T-shirts
  {
    id: 'p5',
    name: 'Signature Polo T-Shirt',
    description: 'A smart-casual staple, our polo t-shirt is crafted from pique cotton for a textured feel and a comfortable fit.',
    price: 59.99,
    rating: 4.7,
    reviewCount: 320,
    category: 'polo-tshirt',
    brand: 'Prestige',
    images: ['https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgO-yMlAsx8RlDNnXCCpKoo1gT25kg43_toC9ccRBYldcV6bAQADPsL8dS-OUtfy8kqy3eFm0MvXRDOuGs3TmU4OWULHIKjto_Dz47ew5Eirqt61cNdNNJ7aOIP4vSkD8R8ZmtR7ommjbKMTcIJi1pqr2-L3x4ycnquhh5RUzwYfeBLMxVdyaj10b8Ex90/s320/621784538389b-square.jpg'],
    stock: 100,
    tags: ['polo', 'smart-casual', 'classic'],
  },
  {
    id: 'p9',
    name: 'Premium Polo',
    description: 'A premium polo shirt for a sharp look.',
    price: 45.5,
    rating: 4.8,
    reviewCount: 120,
    category: 'polo-tshirt',
    brand: 'Polo Kings',
    images: ['https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh1t7xezvuryEwkm18rKIZ660Gbcqi5-Ys-S05EXlzfd7-CB1F0tINwJpBpMJDFPdlzc8RKiwv6Xf8mbw5hT4ebBmGPskRwa3Qmc7ExVlKgSW64wq3K3YsyQV6v9LJzHjl9cuzKL9TeNPLqjwfnAzrxl1K61CDGlVaYO3BNj_2PZQ46CbP4ozL-ESMCK6U/s320/67285487491ac-square.jpg'],
    stock: 50,
    tags: ['polo', 'premium'],
  },
  {
    id: 'p12',
    name: 'Essential Polo Shirt',
    description: 'Your everyday essential polo shirt.',
    price: 49.99,
    rating: 4.6,
    reviewCount: 200,
    category: 'polo-tshirt',
    brand: 'Prestige',
    images: ['https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjmfOh_c2ApBHe2NOTQB_JC6sZozny0x_PgELwKTVuAnj0K0pzpgdWJlOnXLuthSuTv_UgH7AYKaCQMq8fMfJZpchVpy3lJMUvWpqPgHf1a4qQd7-Piy-YUGGcGt7SW78dlrJnWXdkBwsraSv9FcCb_Kp7m_Oxm9V_yRyDtGrI1lspHRfATb9XaxERkKzw/s320/62178453a886d-square.jpg'],
    stock: 110,
    tags: ['polo', 'essential', 'classic'],
  },
  {
    id: 'p15',
    name: 'Sport Polo Shirt',
    description: 'A sporty polo for an active lifestyle.',
    price: 54.99,
    rating: 4.7,
    reviewCount: 180,
    category: 'polo-tshirt',
    brand: 'QuantumFit',
    images: ['https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhbbkGRkXNJWiPloVwyU2vOF32DTx7k4eSPJRL4uaH-r_UCl5mI1H3ssIDN_ek8JXD6PfGaJzUz-Dule7r8_LmgrzJO3A1gmMjjYisZX1KHxOv3E8k5a5DU3DCQzc4mrAfWcet1dcjTjSPk9IePJtxHpyrJta0soTX2ExSx2e32t1DIPH8gFtZywPeNnTg/s320/650182af39a77-square.jpeg'],
    stock: 90,
    tags: ['polo', 'sport', 'activewear'],
  },

  // Other categories
  {
    id: 'p3',
    name: 'Oversized Drop Shoulder Tee',
    description: 'Get the relaxed, modern look with this drop shoulder t-shirt. Its oversized fit offers both comfort and style.',
    price: 34.99,
    rating: 4.8,
    reviewCount: 180,
    category: 'drop-shoulder',
    brand: 'StreetStyle',
    images: ['https://placehold.co/600x600.png'],
    stock: 60,
    tags: ['oversized', 'streetwear', 'new'],
  },
  {
    id: 'p4',
    name: 'Performance Sports T-Shirt',
    description: 'Engineered for athletes, this sports t-shirt features moisture-wicking technology to keep you dry and comfortable during any activity.',
    price: 49.99,
    rating: 4.9,
    reviewCount: 450,
    category: 'sports-tshirt',
    brand: 'QuantumFit',
    images: ['https://placehold.co/600x600.png'],
    stock: 120,
    tags: ['sports', 'performance', 'activewear'],
  },
  {
    id: 'p6',
    name: 'Crisp Oxford Shirt',
    description: 'Look sharp in our classic Oxford shirt. A versatile piece that can be dressed up for work or down for the weekend.',
    price: 79.99,
    rating: 4.6,
    reviewCount: 150,
    category: 'shirt',
    brand: 'Gentleman Co.',
    images: ['https://placehold.co/600x600.png'],
    stock: 75,
    tags: ['oxford', 'formal', 'workwear'],
  },
  {
    id: 'p7',
    name: 'Comfort-Flex Boxer Briefs (3-Pack)',
    description: 'Experience all-day comfort with our boxer briefs, made from a soft and stretchy cotton blend. Features a supportive fit and a no-roll waistband.',
    price: 29.99,
    rating: 4.8,
    reviewCount: 500,
    category: 'underwear',
    brand: 'Urban Basics',
    images: ['https://placehold.co/600x600.png'],
    stock: 300,
    tags: ['boxer-briefs', 'comfort', 'multipack'],
  },
];
